/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DataController;
import Model.Data;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M.Hakim Amransyah
 */
public class PanelData extends javax.swing.JFrame {

    private DataController control;
    
    public PanelData(DataController control,Data data) {
        initComponents();
        this.control = control;
        this.label_data.setText(control.getJenis_data());
        this.setDataToTabel(data);
    }

    private PanelData() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        data = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        label_data = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_atribut = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_set_atribut = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        setData = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_label = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        muatData = new javax.swing.JButton();
        selesai = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_nama_file = new javax.swing.JLabel();
        label_jumlah_fitur = new javax.swing.JLabel();
        label_jumlah_data = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_nama_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pengaturan Data");
        setMinimumSize(new java.awt.Dimension(600, 125));
        setPreferredSize(new java.awt.Dimension(900, 550));

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 526));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        data.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        data.setPreferredSize(new java.awt.Dimension(100, 526));
        data.setLayout(new javax.swing.BoxLayout(data, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setPreferredSize(new java.awt.Dimension(434, 60));
        jPanel7.setLayout(new java.awt.BorderLayout());

        label_data.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        label_data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/data_icon.png"))); // NOI18N
        label_data.setText("Data Latih");
        jPanel7.add(label_data, java.awt.BorderLayout.CENTER);

        data.add(jPanel7);

        jPanel2.setPreferredSize(new java.awt.Dimension(434, 210));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 300));

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel_data);
        if (tabel_data.getColumnModel().getColumnCount() > 0) {
            tabel_data.getColumnModel().getColumn(0).setResizable(false);
            tabel_data.getColumnModel().getColumn(1).setResizable(false);
            tabel_data.getColumnModel().getColumn(2).setResizable(false);
            tabel_data.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        data.add(jPanel2);

        jPanel5.setPreferredSize(new java.awt.Dimension(434, 170));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel12.setLayout(new java.awt.BorderLayout());

        tabel_atribut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Atribut", "Jenis"
            }
        ));
        jScrollPane3.setViewportView(tabel_atribut);

        jPanel12.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Atribut Data", jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel14.setPreferredSize(new java.awt.Dimension(291, 100));
        jPanel14.setLayout(new java.awt.BorderLayout());

        tabel_set_atribut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Atribut", "Kategori/Ordinal", "Kontinu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel_set_atribut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(tabel_set_atribut);
        if (tabel_set_atribut.getColumnModel().getColumnCount() > 0) {
            tabel_set_atribut.getColumnModel().getColumn(1).setResizable(false);
            tabel_set_atribut.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel14.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel14);

        jPanel15.setLayout(new java.awt.BorderLayout());

        setData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/OK.png"))); // NOI18N
        setData.setText("Atur Atribut Data");
        setData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDataActionPerformed(evt);
            }
        });
        jPanel15.add(setData, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel15);

        jTabbedPane1.addTab("Pengaturan Atribut Data", jPanel13);

        jPanel4.setLayout(new java.awt.BorderLayout());

        tabel_label.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Label"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabel_label);
        if (tabel_label.getColumnModel().getColumnCount() > 0) {
            tabel_label.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel4.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Label", jPanel4);

        jTabbedPane1.setSelectedIndex(1);

        jPanel5.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        data.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(434, 40));
        jPanel6.setLayout(new java.awt.BorderLayout());

        muatData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/browse.png"))); // NOI18N
        muatData.setText("Telusuri Data");
        muatData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        muatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muatDataActionPerformed(evt);
            }
        });
        jPanel6.add(muatData, java.awt.BorderLayout.CENTER);

        selesai.setText("Selesai");
        selesai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });
        jPanel6.add(selesai, java.awt.BorderLayout.LINE_END);

        data.add(jPanel6);

        jPanel1.add(data);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMinimumSize(new java.awt.Dimension(80, 28));
        jPanel3.setPreferredSize(new java.awt.Dimension(80, 526));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel10.setPreferredSize(new java.awt.Dimension(349, 58));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/info.png"))); // NOI18N
        jLabel2.setText("Keterangan");
        jPanel10.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel10);

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setPreferredSize(new java.awt.Dimension(349, 440));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nama File");

        jLabel3.setText("Jumlah Fitur");

        jLabel4.setText("Jumlah Data");

        label_nama_file.setText("-");

        label_jumlah_fitur.setText("0");

        label_jumlah_data.setText("0");

        jLabel5.setText("Label");

        label_nama_label.setText("-");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(104, 104, 104)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label_nama_file, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_jumlah_fitur, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(label_jumlah_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(label_nama_label, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_nama_file))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(label_jumlah_fitur))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(label_jumlah_data))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(label_nama_label))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9);

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void muatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muatDataActionPerformed
        try {
            this.setDataToTabel(this.control.muatData(jPanel1));
        } catch (IOException ex) {
            Logger.getLogger(PanelData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_muatDataActionPerformed

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        this.dispose();
    }//GEN-LAST:event_selesaiActionPerformed

    private void setDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDataActionPerformed
       DefaultTableModel tabel = (DefaultTableModel) this.tabel_set_atribut.getModel();
        System.out.println("");
       for(int i=0;i<tabel.getRowCount();i++){
          if(tabel.getValueAt(i, 1) != null){
              if(tabel.getValueAt(i, 1).toString().equalsIgnoreCase("true")){
                this.control.ubahTipeAtribut(i, "Kategori/Ordinal");   
              }
          }
          if(tabel.getValueAt(i, 2) != null){
              if(tabel.getValueAt(i, 2).toString().equalsIgnoreCase("true")){
                  this.control.ubahTipeAtribut(i, "Kontinu");   
              }
          }    
       }
       this.setDataToTabel(this.control.getData());
       JOptionPane.showMessageDialog(null,"Atribut Data berhasil diperbarui", "Message",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_setDataActionPerformed

    private void setDataToTabel(Data data){
        if(data != null){
            DefaultTableModel tabel = (DefaultTableModel) this.tabel_data.getModel();
            tabel.setRowCount(data.getJumlahData());
            tabel.setColumnCount(data.getJumlahFitur());

            this.label_jumlah_data.setText(data.getJumlahData()+"");
            this.label_jumlah_fitur.setText((data.getJumlahFitur()-1)+"");
            this.label_nama_file.setText(data.getNama_file()+"");
            this.label_nama_label.setText(data.getNamaLabel()+"");
            
            for(int i=0;i<data.getJumlahData();i++){
                for(int j=0;j<data.getJumlahFitur();j++){
                    tabel.setValueAt(data.getFitur().get(j).getKolom_nilai().get(i), i, j);
                }
            } 
            this.setAtributDataToTabel(data);
            this.setPengaturanAtributDataToTabel(data);
            this.setLabelToTabel(data);
        }
    }
    
    private void setAtributDataToTabel(Data data){
        DefaultTableModel tabel = (DefaultTableModel) this.tabel_atribut.getModel();
        tabel.setRowCount(data.getJumlahFitur()-1);
        for(int i=0;i<data.getJumlahFitur()-1;i++){
            tabel.setValueAt(data.getFitur().get(i).getNama_fitur(), i, 0);
            tabel.setValueAt(data.getFitur().get(i).getTipe(), i, 1);
        }
    }
    
    private void setPengaturanAtributDataToTabel(Data data){
        DefaultTableModel tabel = (DefaultTableModel) this.tabel_set_atribut.getModel();
        tabel.setRowCount(data.getJumlahFitur()-1);
        for(int i=0;i<data.getJumlahFitur()-1;i++){
            tabel.setValueAt(data.getFitur().get(i).getNama_fitur(), i, 0);
        }
    }
    
    private void setLabelToTabel(Data data){
        DefaultTableModel tabel = (DefaultTableModel) this.tabel_label.getModel();
        tabel.setRowCount(data.getLabel().size());
        for(int i=0;i<data.getLabel().size();i++){
            tabel.setValueAt(data.getLabel().get(i), i, 0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_data;
    private javax.swing.JLabel label_jumlah_data;
    private javax.swing.JLabel label_jumlah_fitur;
    private javax.swing.JLabel label_nama_file;
    private javax.swing.JLabel label_nama_label;
    private javax.swing.JButton muatData;
    private javax.swing.JButton selesai;
    private javax.swing.JButton setData;
    private javax.swing.JTable tabel_atribut;
    private javax.swing.JTable tabel_data;
    private javax.swing.JTable tabel_label;
    private javax.swing.JTable tabel_set_atribut;
    // End of variables declaration//GEN-END:variables
}
